### ISSUE TITLE
Adding multiple tsl2561's

### ISSUE THREAD

**Issue by msreed817** [ControlEverythingCommunity/TSL2561#1]
I am trying to add three tsl2561's onto one Raspberry Pi using the python code. I know the addresses would be 0x29 for ground, 0x49 for vcc connection addresses. How would I add these sensors to your python code, as well as the original floating 0x39 address? Thanks.

**Comment by zaphod-42** [comment]
These are code samples, you can copy it and change the address that is listed in the commands (0x39) to whichever address you need, this is not actually a fill library and does not have the ability to red 3 sensors simultaniously
